install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - pip install -U tox
  - npm install -g pug-cli
  - python setup.py install

env:
  - TOXENV=py34
  - TOXENV=py36

language: python

python: "3.6"

script: tox

matrix:
  include:
    - python: 3.5
      env:
      - TOXENV=py35
